import type { User, CasoInovacao, ContactMessage } from '../types';

// Dados de demonstração - simulam dados reais sem conexão com banco

export const demoUser: User = {
  id: 'demo-user-123',
  email: 'demo@designario.com',
  nome: 'Maria Silva',
  tipo: 'demo',
  instituicao: 'Universidade Federal do Rio de Janeiro',
  telefone: '(21) 99999-9999',
  bio: 'Extensionista em projetos de inovação social no Rio de Janeiro. Este é um perfil de demonstração.',
  avatar_url: 'https://images.unsplash.com/photo-1494790108755-2616b612b647?w=150&h=150&fit=crop&crop=face',
  ativo: true,
  created_at: '2024-01-15T10:00:00.000Z',
  updated_at: '2024-01-20T14:30:00.000Z',
  isDemo: true
};

export const demoUsers: User[] = [
  {
    id: 'demo-admin-1',
    email: 'admin.demo@designario.com',
    nome: 'Carlos Administrador',
    tipo: 'admin',
    instituicao: 'Coordenação Geral',
    telefone: '(21) 98888-8888',
    bio: 'Administrador do sistema - perfil de demonstração',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    ativo: true,
    created_at: '2024-01-01T09:00:00.000Z',
    updated_at: '2024-01-25T16:00:00.000Z',
    isDemo: true
  },
  {
    id: 'demo-ext-1',
    email: 'joao.extensionista@ufrj.br',
    nome: 'João Extensionista',
    tipo: 'extensionista',
    instituicao: 'UFRJ',
    telefone: '(21) 97777-7777',
    bio: 'Extensionista focado em projetos de educação',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    ativo: true,
    created_at: '2024-01-10T11:00:00.000Z',
    updated_at: '2024-01-22T10:15:00.000Z',
    isDemo: true
  },
  {
    id: 'demo-pesq-1',
    email: 'ana.pesquisadora@uerj.br',
    nome: 'Ana Pesquisadora',
    tipo: 'pesquisador',
    instituicao: 'UERJ',
    telefone: '(21) 96666-6666',
    bio: 'Pesquisadora em inovação social urbana',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    ativo: true,
    created_at: '2024-01-12T14:00:00.000Z',
    updated_at: '2024-01-24T09:30:00.000Z',
    isDemo: true
  },
  {
    id: 'demo-coord-1',
    email: 'pedro.coordenador@puc-rio.br',
    nome: 'Pedro Coordenador',
    tipo: 'coordenador',
    instituicao: 'PUC-Rio',
    telefone: '(21) 95555-5555',
    bio: 'Coordenador de projetos comunitários',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    ativo: true,
    created_at: '2024-01-08T08:30:00.000Z',
    updated_at: '2024-01-23T17:45:00.000Z',
    isDemo: true
  },
  demoUser
];

export const demoCases: CasoInovacao[] = [
  {
    id: 'demo-case-1',
    titulo: 'Horta Comunitária da Rocinha',
    descricao: 'Projeto de agricultura urbana que transformou um terreno abandonado em uma horta comunitária produtiva, oferecendo alimentos frescos e capacitação em agricultura sustentável para moradores da Rocinha.',
    resumo: 'Horta comunitária que produz alimentos orgânicos e promove capacitação em agricultura sustentável',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    bairro: 'Rocinha',
    categoria: 'Meio Ambiente',
    subcategoria: 'Agricultura Urbana',
    imagem_url: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.9915,
    coordenadas_lng: -43.2481,
    pessoas_impactadas: 150,
    orcamento: 25000,
    data_inicio: '2023-03-01',
    status: 'ativo',
    tags: ['agricultura', 'sustentabilidade', 'comunidade'],
    contato_nome: 'Maria das Plantas',
    contato_email: 'maria.plantas@rocinha.org',
    contato_telefone: '(21) 98765-4321',
    extensionista_id: 'demo-ext-1',
    status_ativo: true,
    visualizacoes: 324,
    created_at: '2024-01-15T10:00:00.000Z',
    updated_at: '2024-01-25T14:30:00.000Z',
    extensionista: demoUsers[1]
  },
  {
    id: 'demo-case-2',
    titulo: 'Biblioteca Digital Comunitária',
    descricao: 'Iniciativa que criou uma biblioteca digital acessível para estudantes de comunidades carentes, com computadores, internet gratuita e suporte educacional.',
    resumo: 'Espaço digital de aprendizagem para estudantes de baixa renda',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    bairro: 'Cidade de Deus',
    categoria: 'Educação',
    subcategoria: 'Inclusão Digital',
    imagem_url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.9456,
    coordenadas_lng: -43.3631,
    pessoas_impactadas: 200,
    orcamento: 45000,
    data_inicio: '2023-06-15',
    status: 'ativo',
    tags: ['educação', 'tecnologia', 'inclusão'],
    contato_nome: 'João Bibliotecário',
    contato_email: 'joao@bibliotecadigital.org',
    extensionista_id: 'demo-ext-1',
    status_ativo: true,
    visualizacoes: 256,
    created_at: '2024-01-18T09:15:00.000Z',
    updated_at: '2024-01-26T11:00:00.000Z',
    extensionista: demoUsers[1]
  },
  {
    id: 'demo-case-3',
    titulo: 'Oficina de Costura Sustentável',
    descricao: 'Projeto que ensina técnicas de costura e upcycling para mulheres em situação de vulnerabilidade social, promovendo geração de renda e sustentabilidade.',
    resumo: 'Capacitação em costura sustentável para geração de renda',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    bairro: 'Complexo do Alemão',
    categoria: 'Geração de Renda',
    subcategoria: 'Capacitação Profissional',
    imagem_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.8628,
    coordenadas_lng: -43.2581,
    pessoas_impactadas: 80,
    orcamento: 18000,
    data_inicio: '2023-09-01',
    status: 'ativo',
    tags: ['geração de renda', 'sustentabilidade', 'mulheres'],
    contato_nome: 'Ana Costureira',
    contato_email: 'ana@oficinasustentavel.com',
    contato_telefone: '(21) 99876-5432',
    extensionista_id: 'demo-coord-1',
    status_ativo: true,
    visualizacoes: 189,
    created_at: '2024-01-20T15:30:00.000Z',
    updated_at: '2024-01-27T13:45:00.000Z',
    extensionista: demoUsers[3]
  },
  {
    id: 'demo-case-4',
    titulo: 'Centro Cultural Hip Hop',
    descricao: 'Espaço cultural dedicado à expressão artística através do hip hop, oferecendo oficinas de rap, break, graffiti e DJ para jovens da periferia.',
    resumo: 'Centro de expressão cultural através do movimento hip hop',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    bairro: 'Maré',
    categoria: 'Cultura',
    subcategoria: 'Arte Urbana',
    imagem_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.8419,
    coordenadas_lng: -43.2419,
    pessoas_impactadas: 120,
    orcamento: 32000,
    data_inicio: '2023-04-20',
    status: 'ativo',
    tags: ['cultura', 'juventude', 'arte urbana'],
    contato_nome: 'MC Resistência',
    contato_email: 'mc@hiphopmare.org',
    instagram_url: '@hiphopmare',
    extensionista_id: 'demo-pesq-1',
    status_ativo: true,
    visualizacoes: 445,
    created_at: '2024-01-22T08:20:00.000Z',
    updated_at: '2024-01-28T16:10:00.000Z',
    extensionista: demoUsers[2]
  },
  {
    id: 'demo-case-6',
    titulo: 'Reciclagem de Eletrônicos da Tijuca',
    descricao: 'Ponto de coleta e reciclagem de equipamentos eletrônicos descartados, promovendo conscientização ambiental e economia circular na comunidade.',
    resumo: 'Coleta e reciclagem responsável de eletrônicos descartados',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    bairro: 'Tijuca',
    categoria: 'Tecnologia Social',
    subcategoria: 'Reciclagem',
    imagem_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.9249,
    coordenadas_lng: -43.2311,
    pessoas_impactadas: 200,
    orcamento: 15000,
    data_inicio: '2023-08-01',
    status: 'ativo',
    tags: ['tecnologia', 'meio ambiente', 'reciclagem'],
    contato_nome: 'Tech Verde',
    contato_email: 'contato@techverde.org',
    contato_telefone: '(21) 91234-5678',
    extensionista_id: 'demo-ext-1',
    status_ativo: true,
    visualizacoes: 178,
    created_at: '2024-01-19T13:15:00.000Z',
    updated_at: '2024-01-30T11:45:00.000Z',
    extensionista: demoUsers[1]
  },
  {
    id: 'demo-case-7',
    titulo: 'Creche Comunitária Vila Isabel',
    descricao: 'Espaço educativo para crianças de 0 a 5 anos de famílias em situação de vulnerabilidade social, oferecendo cuidados integrais e educação infantil de qualidade.',
    resumo: 'Creche que atende crianças em situação de vulnerabilidade social',
    cidade: 'Rio de Janeiro',
    estado: 'RJ', 
    bairro: 'Vila Isabel',
    categoria: 'Educação',
    subcategoria: 'Educação Infantil',
    imagem_url: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.9146,
    coordenadas_lng: -43.2525,
    pessoas_impactadas: 60,
    orcamento: 80000,
    data_inicio: '2023-01-15',
    status: 'ativo',
    tags: ['educação infantil', 'cuidados', 'desenvolvimento'],
    contato_nome: 'Maria Educadora',
    contato_email: 'maria@crechevilaisabel.org',
    contato_telefone: '(21) 92345-6789',
    instagram_url: '@crechevilaisabel',
    extensionista_id: 'demo-coord-1',
    status_ativo: true,
    visualizacoes: 289,
    created_at: '2024-01-14T07:30:00.000Z',
    updated_at: '2024-01-31T15:20:00.000Z',
    extensionista: demoUsers[3]
  },
  {
    id: 'demo-case-8',
    titulo: 'Cooperativa de Costureiras de Bangu',
    descricao: 'Cooperativa que reúne costureiras locais para produção de roupas e artesanatos, fortalecendo a economia local e promovendo autonomia financeira das mulheres.',
    resumo: 'Cooperativa de costureiras para geração de renda e autonomia feminina',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    bairro: 'Bangu',
    categoria: 'Geração de Renda',
    subcategoria: 'Cooperativismo',
    imagem_url: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.8689,
    coordenadas_lng: -43.4656,
    pessoas_impactadas: 35,
    orcamento: 22000,
    data_inicio: '2023-05-10',
    status: 'ativo',
    tags: ['cooperativismo', 'mulheres', 'economia solidária'],
    contato_nome: 'Rosa Costureira',
    contato_email: 'rosa@coopbangu.coop',
    contato_telefone: '(21) 93456-7890',
    whatsapp: '5521934567890',
    extensionista_id: 'demo-pesq-1',
    status_ativo: true,
    visualizacoes: 156,
    created_at: '2024-01-17T12:00:00.000Z',
    updated_at: '2024-02-01T10:30:00.000Z',
    extensionista: demoUsers[2]
  },
  {
    id: 'demo-case-5',
    titulo: 'Clínica de Saúde Mental Comunitária',
    descricao: 'Atendimento psicológico gratuito para moradores de comunidades, com foco em saúde mental, violência doméstica e dependência química.',
    resumo: 'Atendimento psicológico gratuito para comunidades carentes',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    bairro: 'Santa Teresa',
    categoria: 'Saúde',
    subcategoria: 'Saúde Mental',
    imagem_url: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=600&fit=crop&crop=center',
    coordenadas_lat: -22.9156,
    coordenadas_lng: -43.1892,
    pessoas_impactadas: 95,
    orcamento: 55000,
    data_inicio: '2023-02-10',
    status: 'ativo',
    tags: ['saúde mental', 'psicologia', 'bem-estar'],
    contato_nome: 'Dra. Clara Mente',
    contato_email: 'clara@saudemental.org',
    contato_telefone: '(21) 94567-8901',
    extensionista_id: 'demo-ext-1',
    status_ativo: true,
    visualizacoes: 312,
    created_at: '2024-01-16T12:45:00.000Z',
    updated_at: '2024-01-29T09:20:00.000Z',
    extensionista: demoUsers[1]
  }
];

export const demoMessages: ContactMessage[] = [
  {
    id: 'demo-msg-1',
    nome: 'Carlos Silva',
    email: 'carlos.silva@email.com',
    telefone: '(21) 99123-4567',
    assunto: 'Solicitação de acesso como extensionista',
    mensagem: 'Olá! Sou professor da UFRJ e gostaria de solicitar acesso como extensionista na plataforma. Trabalho com projetos de sustentabilidade urbana e acredito que posso contribuir significativamente.',
    tipo_solicitacao: 'acesso',
    status: 'pendente',
    created_at: '2024-01-29T14:30:00.000Z',
    updated_at: '2024-01-29T14:30:00.000Z'
  },
  {
    id: 'demo-msg-2',
    nome: 'Fernanda Costa',
    email: 'fernanda@ong.org.br',
    telefone: '(21) 98765-4321',
    assunto: 'Dúvida sobre cadastro de projeto',
    mensagem: 'Gostaria de saber como funciona o processo para cadastrar um projeto de nossa ONG na plataforma. Temos uma iniciativa de educação infantil que pode ser interessante.',
    tipo_solicitacao: 'duvida',
    status: 'lido',
    created_at: '2024-01-28T10:15:00.000Z',
    updated_at: '2024-01-28T15:45:00.000Z'
  },
  {
    id: 'demo-msg-3',
    nome: 'Roberto Santos',
    email: 'roberto.santos@gmail.com',
    assunto: 'Sugestão para melhoria da plataforma',
    mensagem: 'Parabéns pela iniciativa! Sugiro que seja implementado um sistema de favoritos para que usuários possam marcar projetos de interesse. Seria muito útil!',
    tipo_solicitacao: 'sugestao',
    status: 'respondido',
    created_at: '2024-01-26T16:20:00.000Z',
    updated_at: '2024-01-27T09:10:00.000Z'
  },
  {
    id: 'demo-msg-4',
    nome: 'Juliana Oliveira',
    email: 'juliana.o@hotmail.com',
    telefone: '(21) 97654-3210',
    assunto: 'Parceria para divulgação de projetos',
    mensagem: 'Represento um coletivo de comunicação popular e gostaríamos de discutir uma possível parceria para divulgação dos projetos cadastrados na plataforma.',
    tipo_solicitacao: 'outro',
    status: 'pendente',
    created_at: '2024-01-25T13:40:00.000Z',
    updated_at: '2024-01-25T13:40:00.000Z'
  },
  {
    id: 'demo-msg-5',
    nome: 'Marcos Pereira',
    email: 'marcos.pereira@unirio.br',
    assunto: 'Acesso como pesquisador',
    mensagem: 'Sou pesquisador da UNIRIO na área de políticas públicas e inovação social. Gostaria de ter acesso à plataforma para fins de pesquisa acadêmica.',
    tipo_solicitacao: 'acesso',
    status: 'lido',
    created_at: '2024-01-24T11:05:00.000Z',
    updated_at: '2024-01-24T17:30:00.000Z'
  }
];

export const getDemoUnreadCount = (): number => {
  return demoMessages.filter(msg => msg.status === 'pendente').length;
};